trigger:
  - azure-pipelines-0909  # Or your desired branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '15'
      addToPath: true
      architecture: 'x64'

  - script: |
      java -version
      mvn -version
    displayName: 'Check Java and Maven versions'

  - script: 'mvn clean install'
    displayName: 'Run Maven build'
