trigger:
  - azure-pipelines-07232023  # Or your desired branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '20'  # Update this to the correct version when Java 20 is available
      addToPath: true

  - script: |
      java -version
    displayName: 'Print Java Version'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'  # Update with the correct path
      goals: 'clean install'  # Update with your desired Maven goals
      publishJUnitResults: false
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
    displayName: 'Run Maven Goals'

